name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Image
      run: docker build -t devops-app .

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: devops-app
        severity: CRITICAL
        exit-code: '1'
